
-- Additional tables for Consumer App & Support & Store Management

-- 6. BANNERS Table
create table public.banners (
  id bigint generated by default as identity primary key,
  image_url text not null,
  link text,
  order_index int default 0,
  type text default 'main', -- 'main', 'category', 'brand', 'campaign'
  title text,
  description text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.banners enable row level security;

create policy "Banners are viewable by everyone." on public.banners
  for select using (is_active = true);

create policy "Admins can manage banners." on public.banners
  for all using (
    exists (
      select 1 from public.users 
      where users.id = auth.uid() and users.role = 'admin'
    )
  );

-- 7. CATEGORIES Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon_name text,
  image_url text,
  order_index int default 0,
  parent_id bigint references public.categories(id),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.categories enable row level security;

create policy "Categories are viewable by everyone." on public.categories
  for select using (is_active = true);

create policy "Admins can manage categories." on public.categories
  for all using (
    exists (
      select 1 from public.users 
      where users.id = auth.uid() and users.role = 'admin'
    )
  );

-- 8. SUPPORT TICKETS Table
create table public.support_tickets (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id), -- Link to auth user
  user_type text default 'user', -- 'user', 'seller'
  category text,
  subject text,
  description text,
  status text default 'open', -- 'open', 'in_progress', 'closed', 'resolved'
  priority text default 'medium', -- 'low', 'medium', 'high'
  assigned_to uuid references auth.users(id), -- Admin ID
  
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.support_tickets enable row level security;

create policy "Users can view their own tickets." on public.support_tickets
  for select using (auth.uid() = user_id);

create policy "Users can create tickets." on public.support_tickets
  for insert with check (auth.uid() = user_id);

create policy "Admins can view all tickets." on public.support_tickets
  for select using (
    exists (
      select 1 from public.users 
      where users.id = auth.uid() and users.role = 'admin'
    )
  );

create policy "Admins can update tickets." on public.support_tickets
  for update using (
    exists (
      select 1 from public.users 
      where users.id = auth.uid() and users.role = 'admin'
    )
  );

-- 9. STORE SUB ADMINS Table
create table public.store_sub_admins (
  id uuid default uuid_generate_v4() primary key,
  store_id uuid references public.stores(seller_id),
  email text,
  phone text,
  permissions text[], -- Array of permission strings
  status text default 'invited', -- 'invited', 'active'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.store_sub_admins enable row level security;

create policy "Store owners can manage sub admins." on public.store_sub_admins
  for all using (auth.uid() = store_id);

-- 10. STORE DELETION REQUESTS Table
create table public.store_deletion_requests (
  id uuid default uuid_generate_v4() primary key,
  seller_id uuid references public.stores(seller_id),
  reason text,
  status text default 'pending', -- 'pending', 'approved', 'rejected'
  admin_note text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone
);

alter table public.store_deletion_requests enable row level security;

create policy "Store owners can create deletion requests." on public.store_deletion_requests
  for insert with check (auth.uid() = seller_id);

create policy "Store owners can view their requests." on public.store_deletion_requests
  for select using (auth.uid() = seller_id);

create policy "Admins can manage deletion requests." on public.store_deletion_requests
  for all using (
    exists (
      select 1 from public.users 
      where users.id = auth.uid() and users.role = 'admin'
    )
  );
