#!/bin/bash
set -e

SUPABASE_URL="https://ihmixxzqnpamcwmrfibx.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlobWl4eHpxbnBhbWN3bXJmaWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MDE0NTEsImV4cCI6MjA4NzI3NzQ1MX0.EZkjZAq2mwg-gfBhwotAGp4stb1D-rmWHuzVsz2yzX0"

FIREBASE_WEB_API_KEY="AIzaSyBOk7kLeb_K6J97XZUi5nx4H3VBXOLYp5o"
FIREBASE_WEB_APP_ID="1:926056125070:web:717e3e1b56f678286cefdf"
FIREBASE_PROJECT_ID="ibul-ecommerce"
FIREBASE_AUTH_DOMAIN="ibul-ecommerce.firebaseapp.com"
FIREBASE_STORAGE_BUCKET="ibul-ecommerce.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID="926056125070"
FIREBASE_WEB_MEASUREMENT_ID="G-Y7M1GD96GL"

echo "Web build config kontrol:"
echo "IBUL_SUPABASE_URL=$SUPABASE_URL"
echo "IBUL_FIREBASE_WEB_API_KEY=$FIREBASE_WEB_API_KEY"
echo "IBUL_FIREBASE_WEB_APP_ID=$FIREBASE_WEB_APP_ID"
echo "IBUL_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_ENDER_ID"
echo "IBUL_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID"
echo "IBUL_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN"
echo "IBUL_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET"
echo "IBUL_FIREBASE_WEB_MEASUREMENT_ID=$FIREBASE_WEB_MEASUREMENT_ID"

flutter clean
flutter pub get

flutter build web --release --pwa-strategy=none --no-wasm-dry-run \
  --target lib/main.dart \
  --dart-define=IBUL_SUPABASE_URL="$SUPABASE_URL" \
  --dart-define=IBUL_SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
  --dart-define=IBUL_FIREBASE_WEB_API_KEY="$FIREBASE_WEB_API_KEY" \
  --dart-define=IBUL_FIREBASE_WEB_APP_ID="$FIREBASE_WEB_APP_ID" \
  --dart-define=IBUL_FIREBASE_MESSAGING_SENDER_ID="$FIREBASE_MESSAGING_SENDER_ID" \
  --dart-define=IBUL_FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID" \
  --dart-define=IBUL_FIREBASE_AUTH_DOMAIN="$FIREBASE_AUTH_DOMAIN" \
  --dart-define=IBUL_FIREBASE_STORAGE_BUCKET="$FIREBASE_STORAGE_BUCKET" \
  --dart-define=IBUL_FIREBASE_WEB_MEASUREMENT_ID="$FIREBASE_WEB_MEASUREMENT_ID"

cd ..

firebase deploy --only hosting
