-- Fix: public.categories tablosunu oluştur ve erişim izinlerini ayarla.
-- Hata: relation "public.categories" does not exist → tablo hiç oluşturulmamış.
-- Supabase SQL Editor'de çalıştır.

-- 1. Tabloyu oluştur (zaten varsa dokunma)
create table if not exists public.categories (
  id        bigint generated by default as identity primary key,
  name      text not null,
  icon_name text,
  image_url text,
  order_index int default 0,
  parent_id bigint references public.categories(id) on delete cascade,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. RLS'yi etkinleştir
alter table public.categories enable row level security;

-- 3. Grant izinleri
grant usage on schema public to anon, authenticated;
grant select on public.categories to anon, authenticated;
grant insert, update, delete on public.categories to authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;

-- 4. Okuma politikası: aktif kategoriler herkese görünür
drop policy if exists "Categories are viewable by everyone." on public.categories;
create policy "Categories are viewable by everyone."
  on public.categories
  for select
  to anon, authenticated
  using (is_active = true);

-- 5. Yazma politikası: admin_user_permissions veya users.role üzerinden yetkilendir
drop policy if exists "Admins can manage categories." on public.categories;
create policy "Admins can manage categories."
  on public.categories
  for all
  to authenticated
  using (
    exists (
      select 1 from public.admin_user_permissions aup
      where aup.user_id = auth.uid() and aup.is_active = true
    )
    or
    exists (
      select 1 from public.users u
      where u.id = auth.uid() and u.role in ('admin', 'super_admin')
    )
  )
  with check (
    exists (
      select 1 from public.admin_user_permissions aup
      where aup.user_id = auth.uid() and aup.is_active = true
    )
    or
    exists (
      select 1 from public.users u
      where u.id = auth.uid() and u.role in ('admin', 'super_admin')
    )
  );

-- 6. Adminler pasif kategorileri de görebilmeli
drop policy if exists "Admins can view all categories." on public.categories;
create policy "Admins can view all categories."
  on public.categories
  for select
  to authenticated
  using (
    exists (
      select 1 from public.admin_user_permissions aup
      where aup.user_id = auth.uid() and aup.is_active = true
    )
    or
    exists (
      select 1 from public.users u
      where u.id = auth.uid() and u.role in ('admin', 'super_admin')
    )
  );

-- 7. PostgREST şema önbelleğini yenile
notify pgrst, 'reload schema';

-- 8. Doğrulama: tablo yapısını ve kategorileri göster
select id, name, parent_id, is_active, order_index
from public.categories
order by parent_id nulls first, order_index;
