-- app_categories: Mobil ana sayfadaki 8 kategori kutusunun görselleri
create table if not exists public.app_categories (
  id bigint generated by default as identity primary key,
  category_key text not null unique,
  display_name text not null,
  image_url text,
  is_active boolean not null default true
);

insert into public.app_categories (category_key, display_name, image_url, is_active)
values
  ('yakin_lokasyon', 'Yakın Lokasyon', null, true),
  ('urun_listele', 'Ürün Listele', null, true),
  ('gorsel_zeka', 'Görsel Zeka', null, true),
  ('urun_parcala', 'Ürün Parçala', null, true),
  ('ibul_premium', 'İBUL Premium', null, true),
  ('bana_ozel', 'Bana Özel', null, true),
  ('hizli_yemek', 'Hızlı Yemek', null, true),
  ('yapay_zeka', 'Yapay Zeka', null, true)
on conflict (category_key) do update
set
  display_name = excluded.display_name,
  is_active = excluded.is_active;
