-- Geofence push altyapısı (FCM + backend cron)

create table if not exists public.push_device_tokens (
  token text primary key,
  user_id uuid references auth.users(id) on delete cascade,
  platform text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_live_locations (
  user_id uuid primary key references auth.users(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_product_interests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  interest_type text not null check (interest_type in ('searched', 'favorite', 'saved', 'cart')),
  term text not null,
  created_at timestamptz not null default now(),
  unique(user_id, interest_type, term)
);

alter table public.user_product_interests
drop constraint if exists user_product_interests_interest_type_check;

alter table public.user_product_interests
add constraint user_product_interests_interest_type_check
check (interest_type in ('searched', 'favorite', 'saved', 'cart'));

create table if not exists public.push_notification_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text,
  seller_id text,
  store_name text,
  interest_type text,
  term text,
  distance_meters int,
  sent_at timestamptz not null default now(),
  payload jsonb
);

create index if not exists idx_push_device_tokens_user on public.push_device_tokens(user_id);
create index if not exists idx_user_live_locations_updated on public.user_live_locations(updated_at desc);
create index if not exists idx_user_product_interests_user on public.user_product_interests(user_id);
create index if not exists idx_push_notification_logs_lookup on public.push_notification_logs(user_id, seller_id, sent_at desc);

alter table public.push_device_tokens enable row level security;
alter table public.user_live_locations enable row level security;
alter table public.user_product_interests enable row level security;
alter table public.push_notification_logs enable row level security;

drop policy if exists "push_device_tokens_own_select" on public.push_device_tokens;
create policy "push_device_tokens_own_select"
on public.push_device_tokens
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "push_device_tokens_own_upsert" on public.push_device_tokens;
create policy "push_device_tokens_own_upsert"
on public.push_device_tokens
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_live_locations_own_all" on public.user_live_locations;
create policy "user_live_locations_own_all"
on public.user_live_locations
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_product_interests_own_all" on public.user_product_interests;
create policy "user_product_interests_own_all"
on public.user_product_interests
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "push_notification_logs_own_select" on public.push_notification_logs;
create policy "push_notification_logs_own_select"
on public.push_notification_logs
for select
to authenticated
using (auth.uid() = user_id);
