/// Local, searchable catalog. Not a live OEM API — extend here or swap later.
const kVehicleBrandModels = <String, List<String>>{
  'BMW': [
    '1 Serisi',
    '2 Serisi',
    '3 Serisi',
    '4 Serisi',
    '5 Serisi',
    '6 Serisi',
    '7 Serisi',
    '8 Serisi',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'XM',
    'Z4',
    'i4',
    'i5',
    'i7',
    'iX',
    'iX1',
    'iX2',
    'M2',
    'M3',
    'M4',
    'M5',
  ],
  'BMW Motorrad': ['R 1250 GS', 'R 1300 GS', 'S 1000 RR', 'F 900 R'],
  'Mercedes-Benz': [
    'A Serisi',
    'B Serisi',
    'C Serisi',
    'E Serisi',
    'S Serisi',
    'CLA',
    'CLS',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'G Serisi',
    'EQA',
    'EQB',
    'EQE',
    'EQS',
    'Vito',
    'Sprinter',
    'V Serisi',
  ],
  'Audi': [
    'A1',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Q2',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'e-tron',
    'Q4 e-tron',
    'TT',
  ],
  'Volkswagen': [
    'Polo',
    'Golf',
    'Passat',
    'Arteon',
    'T-Roc',
    'T-Cross',
    'Tiguan',
    'Touareg',
    'Caddy',
    'Transporter',
    'ID.3',
    'ID.4',
    'ID.7',
  ],
  'Toyota': [
    'Corolla',
    'Corolla Cross',
    'C-HR',
    'Yaris',
    'Yaris Cross',
    'Camry',
    'RAV4',
    'Hilux',
    'Land Cruiser',
    'Proace',
  ],
  'Renault': [
    'Clio',
    'Megane',
    'Megane E-Tech',
    'Captur',
    'Austral',
    'Kadjar',
    'Talisman',
    'Symbol',
    'Kangoo',
    'Trafic',
  ],
  'Fiat': ['Egea', 'Tipo', '500', 'Panda', 'Doblo', 'Fiorino', 'Fullback'],
  'Ford': [
    'Focus',
    'Fiesta',
    'Puma',
    'Kuga',
    'Mustang',
    'Ranger',
    'Transit',
    'Tourneo Custom',
  ],
  'Opel': [
    'Corsa',
    'Astra',
    'Insignia',
    'Mokka',
    'Crossland',
    'Grandland',
    'Combo',
  ],
  'Peugeot': ['208', '308', '408', '2008', '3008', '5008', 'Partner', 'Expert'],
  'Citroën': ['C3', 'C4', 'C5 Aircross', 'Berlingo', 'Jumpy'],
  'Hyundai': [
    'i10',
    'i20',
    'i30',
    'Elantra',
    'Bayon',
    'Kona',
    'Tucson',
    'Santa Fe',
    'Ioniq 5',
    'Ioniq 6',
  ],
  'Kia': [
    'Picanto',
    'Rio',
    'Ceed',
    'Stonic',
    'XCeed',
    'Sportage',
    'Sorento',
    'EV6',
    'EV3',
  ],
  'Honda': ['Civic', 'City', 'Jazz', 'HR-V', 'CR-V', 'ZR-V'],
  'Nissan': ['Micra', 'Qashqai', 'Juke', 'X-Trail', 'Navara', 'Leaf'],
  'Skoda': [
    'Fabia',
    'Scala',
    'Octavia',
    'Superb',
    'Kamiq',
    'Karoq',
    'Kodiaq',
    'Enyaq',
  ],
  'Volvo': ['S60', 'S90', 'V60', 'XC40', 'XC60', 'XC90', 'EX30', 'EX90'],
  'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X'],
  'BYD': ['Atto 3', 'Seal', 'Seal U', 'Dolphin', 'Han'],
  'Chery': ['Omoda 5', 'Tiggo 7 Pro', 'Tiggo 8 Pro'],
  'Togg': ['T10X', 'T10F'],
  'Dacia': ['Sandero', 'Duster', 'Jogger', 'Spring', 'Logan'],
  'Seat': ['Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco'],
  'Cupra': ['Formentor', 'Leon', 'Born', 'Tavascan'],
  'Mazda': ['2', '3', 'CX-3', 'CX-30', 'CX-5', 'MX-5'],
  'Suzuki': ['Swift', 'Vitara', 'S-Cross', 'Jimny'],
  'Mitsubishi': ['L200', 'Eclipse Cross', 'ASX', 'Outlander'],
  'Jeep': ['Renegade', 'Compass', 'Wrangler', 'Grand Cherokee', 'Avenger'],
  'Land Rover': [
    'Defender',
    'Discovery',
    'Discovery Sport',
    'Range Rover',
    'Range Rover Sport',
    'Range Rover Evoque',
    'Range Rover Velar',
  ],
  'Mini': ['Cooper', 'Countryman', 'Clubman'],
  'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', 'Boxster'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', 'Junior'],
};

const kVehicleTrims = <String, List<String>>{
  'BMW|3 Serisi': [
    '316i',
    '318i',
    '320i',
    '320i M Sport',
    '330i',
    '330e',
    'M340i',
    'M3',
  ],
  'BMW|5 Serisi': ['520i', '520d', '530i', '530e', 'M550i', 'M5'],
  'BMW|X5': ['xDrive30d', 'xDrive40i', 'xDrive50e', 'M60i', 'X5 M'],
  'Mercedes-Benz|C Serisi': ['C 180', 'C 200', 'C 220 d', 'C 300', 'AMG C 43'],
  'Mercedes-Benz|E Serisi': ['E 200', 'E 220 d', 'E 300', 'AMG E 53'],
  'Mercedes-Benz|GLC': ['GLC 200', 'GLC 220 d', 'GLC 300', 'AMG GLC 43'],
  'Audi|A4': ['30 TDI', '35 TFSI', '40 TDI', 'S4', 'RS 4'],
  'Audi|A3': ['30 TFSI', '35 TFSI', '35 TDI', 'S3'],
  'Volkswagen|Golf': ['1.0 TSI', '1.5 TSI', '2.0 TDI', 'GTI', 'R'],
  'Volkswagen|Passat': ['1.5 TSI', '2.0 TDI', 'Elegance', 'R-Line'],
  'Toyota|Corolla': [
    '1.5 Dream',
    '1.5 Flame',
    '1.8 Hybrid Dream',
    '1.8 Hybrid Flame',
  ],
  'Toyota|C-HR': ['1.8 Hybrid', '2.0 Hybrid'],
  'Renault|Clio': ['1.0 TCe', 'Equilibre', 'Techno', 'Esprit Alpine'],
  'Fiat|Egea': ['Easy', 'Urban', 'Lounge', 'Cross'],
  'Ford|Focus': ['Trend', 'Titanium', 'ST-Line', 'ST'],
  'Hyundai|Tucson': ['Style', 'Comfort', 'Elite', 'Platinum'],
  'Kia|Sportage': ['Cool', 'Comfort', 'Prestige', 'GT-Line'],
  'Honda|Civic': ['Elegance', 'Executive', 'Sport', 'Type R'],
  'Togg|T10X': ['V1 RWD', 'V1 AWD', 'V2 RWD', 'V2 AWD'],
  'Tesla|Model Y': ['RWD', 'Long Range', 'Performance'],
  'Tesla|Model 3': ['RWD', 'Long Range', 'Performance'],
};
