// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOk7kLeb_K6J97XZUi5nx4H3VBXOLYp5o',
    appId: '1:926056125070:web:717e3e1b56f678286cefdf',
    messagingSenderId: '926056125070',
    projectId: 'ibul-ecommerce',
    authDomain: 'ibul-ecommerce.firebaseapp.com',
    storageBucket: 'ibul-ecommerce.firebasestorage.app',
    measurementId: 'G-Y7M1GD96GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBir4mFOOwkTXj5ykRNFLkv_Gto9TyBT5M',
    appId: '1:926056125070:android:5be2c001a895e7116cefdf',
    messagingSenderId: '926056125070',
    projectId: 'ibul-ecommerce',
    storageBucket: 'ibul-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZcy4ycUb7Y4r0aLBis_lAuxVvJ7iJ00A',
    appId: '1:926056125070:ios:1a75a9ffd685e2c96cefdf',
    messagingSenderId: '926056125070',
    projectId: 'ibul-ecommerce',
    storageBucket: 'ibul-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.ibulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZcy4ycUb7Y4r0aLBis_lAuxVvJ7iJ00A',
    appId: '1:926056125070:ios:1a75a9ffd685e2c96cefdf',
    messagingSenderId: '926056125070',
    projectId: 'ibul-ecommerce',
    storageBucket: 'ibul-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.ibulApp',
  );
}
