class TurkiyeLocationData {
  const TurkiyeLocationData._();

  static const List<String> provinces = <String>[
    'Adana',
    'Adıyaman',
    'Afyonkarahisar',
    'Ağrı',
    'Aksaray',
    'Amasya',
    'Ankara',
    'Antalya',
    'Ardahan',
    'Artvin',
    'Aydın',
    'Balıkesir',
    'Bartın',
    'Batman',
    'Bayburt',
    'Bilecik',
    'Bingöl',
    'Bitlis',
    'Bolu',
    'Burdur',
    'Bursa',
    'Çanakkale',
    'Çankırı',
    'Çorum',
    'Denizli',
    'Diyarbakır',
    'Düzce',
    'Edirne',
    'Elazığ',
    'Erzincan',
    'Erzurum',
    'Eskişehir',
    'Gaziantep',
    'Giresun',
    'Gümüşhane',
    'Hakkari',
    'Hatay',
    'Iğdır',
    'Isparta',
    'İstanbul',
    'İzmir',
    'Kahramanmaraş',
    'Karabük',
    'Karaman',
    'Kars',
    'Kastamonu',
    'Kayseri',
    'Kırıkkale',
    'Kırklareli',
    'Kırşehir',
    'Kilis',
    'Kocaeli',
    'Konya',
    'Kütahya',
    'Malatya',
    'Manisa',
    'Mardin',
    'Mersin',
    'Muğla',
    'Muş',
    'Nevşehir',
    'Niğde',
    'Ordu',
    'Osmaniye',
    'Rize',
    'Sakarya',
    'Samsun',
    'Siirt',
    'Sinop',
    'Sivas',
    'Şanlıurfa',
    'Şırnak',
    'Tekirdağ',
    'Tokat',
    'Trabzon',
    'Tunceli',
    'Uşak',
    'Van',
    'Yalova',
    'Yozgat',
    'Zonguldak',
  ];

  static const Map<String, List<String>> districtsByProvince =
      <String, List<String>>{
        'İstanbul': <String>[
          'Adalar',
          'Arnavutköy',
          'Ataşehir',
          'Avcılar',
          'Bağcılar',
          'Bahçelievler',
          'Bakırköy',
          'Başakşehir',
          'Bayrampaşa',
          'Beşiktaş',
          'Beykoz',
          'Beylikdüzü',
          'Beyoğlu',
          'Büyükçekmece',
          'Çatalca',
          'Çekmeköy',
          'Esenler',
          'Esenyurt',
          'Eyüpsultan',
          'Fatih',
          'Gaziosmanpaşa',
          'Güngören',
          'Kadıköy',
          'Kağıthane',
          'Kartal',
          'Küçükçekmece',
          'Maltepe',
          'Pendik',
          'Sancaktepe',
          'Sarıyer',
          'Silivri',
          'Sultanbeyli',
          'Sultangazi',
          'Şile',
          'Şişli',
          'Tuzla',
          'Ümraniye',
          'Üsküdar',
          'Zeytinburnu',
        ],
        'Ankara': <String>[
          'Altındağ',
          'Ayaş',
          'Bala',
          'Beypazarı',
          'Çankaya',
          'Etimesgut',
          'Gölbaşı',
          'Kahramankazan',
          'Keçiören',
          'Mamak',
          'Polatlı',
          'Sincan',
          'Yenimahalle',
        ],
        'İzmir': <String>[
          'Aliağa',
          'Balçova',
          'Bayraklı',
          'Bornova',
          'Buca',
          'Çeşme',
          'Gaziemir',
          'Karabağlar',
          'Karşıyaka',
          'Konak',
          'Menemen',
          'Narlıdere',
          'Torbalı',
        ],
        'Bursa': <String>[
          'Gemlik',
          'Gürsu',
          'İnegöl',
          'Mudanya',
          'Nilüfer',
          'Osmangazi',
          'Yıldırım',
        ],
        'Antalya': <String>[
          'Aksu',
          'Alanya',
          'Döşemealtı',
          'Kepez',
          'Konyaaltı',
          'Kumluca',
          'Manavgat',
          'Muratpaşa',
          'Serik',
        ],
        'Hatay': <String>[
          'Altınözü',
          'Antakya',
          'Arsuz',
          'Belen',
          'Defne',
          'Dörtyol',
          'Erzin',
          'Hassa',
          'İskenderun',
          'Kırıkhan',
          'Kumlu',
          'Payas',
          'Reyhanlı',
          'Samandağ',
          'Yayladağı',
        ],
        'Adana': <String>[
          'Çukurova',
          'Sarıçam',
          'Seyhan',
          'Yüreğir',
          'Ceyhan',
          'Kozan',
        ],
        'Mersin': <String>[
          'Akdeniz',
          'Erdemli',
          'Mezitli',
          'Silifke',
          'Tarsus',
          'Toroslar',
          'Yenişehir',
        ],
        'Kocaeli': <String>[
          'Başiskele',
          'Çayırova',
          'Darıca',
          'Derince',
          'Gebze',
          'Gölcük',
          'İzmit',
          'Karamürsel',
          'Kartepe',
          'Körfez',
        ],
        'Konya': <String>[
          'Akşehir',
          'Beyşehir',
          'Ereğli',
          'Karatay',
          'Meram',
          'Selçuklu',
        ],
        'Gaziantep': <String>[
          'Araban',
          'İslahiye',
          'Nizip',
          'Nurdağı',
          'Oğuzeli',
          'Şahinbey',
          'Şehitkamil',
        ],
        'Eskişehir': <String>[
          'Odunpazarı',
          'Tepebaşı',
          'Sivrihisar',
          'Alpu',
          'İnönü',
        ],
        'Trabzon': <String>[
          'Akçaabat',
          'Araklı',
          'Arsin',
          'Ortahisar',
          'Sürmene',
          'Yomra',
        ],
        'Şanlıurfa': <String>[
          'Eyyübiye',
          'Haliliye',
          'Karaköprü',
          'Siverek',
          'Viranşehir',
        ],
      };

  static List<String> districtsForProvince(String province) {
    final options = districtsByProvince[province];
    if (options == null || options.isEmpty) {
      return const <String>['Merkez'];
    }
    return List<String>.from(options);
  }

  static String defaultDistrictForProvince(String province) {
    final options = districtsForProvince(province);
    return options.isNotEmpty ? options.first : 'Merkez';
  }
}
