import {
  BillSplitPlan,
  Customer,
  OrderItem,
  OrderStatus,
  Product,
  ProductCategory,
  PrinterJob,
  RestaurantStoreState,
  RestaurantTable,
  ServiceChildItem,
  TableOrder,
} from "@/lib/types";
import {
  addLog,
  buildProductOrderItem,
  calculateOrderTotal,
  cloneOrderItem,
  deriveTableStatus,
  emptyCustomizations,
} from "@/lib/restaurant";

export const productCategories: ProductCategory[] = [
  { id: "popular", name: "Hizli Oneriler", description: "En hizli akan urunler" },
  { id: "grill", name: "Izgara", description: "Ana sicaklar" },
  { id: "appetizer", name: "Baslangic", description: "Meze ve paylasimliklar" },
  { id: "drink", name: "Icecek", description: "Sicak ve soguk icecekler" },
  { id: "dessert", name: "Tatli", description: "Servis sonrasi tatlilar" },
  { id: "service", name: "Servis", description: "Karisik servis ve setler" },
];

export const products: Product[] = [
  {
    id: "truffle-burger",
    name: "Truf Burger",
    categoryId: "grill",
    price: 435,
    kind: "standard",
    description: "Brioche ekmek, cheddar, truf mayo ve karamelize sogan.",
    stockState: "in_stock",
    stockLabel: "Stokta",
    prepMinutes: 18,
    visualTone: "plum",
    isFavorite: true,
    isPopular: true,
    suggestionIds: ["mineral-water", "cheesecake"],
  },
  {
    id: "salmon",
    name: "Izgara Somon",
    categoryId: "grill",
    price: 520,
    kind: "standard",
    description: "Taze somon, limon beurre blanc ve otlu patates.",
    stockState: "in_stock",
    stockLabel: "Hazir",
    prepMinutes: 22,
    visualTone: "blue",
    isPopular: true,
  },
  {
    id: "pasta-bolognese",
    name: "Bolonez Makarna",
    categoryId: "grill",
    price: 360,
    kind: "standard",
    description: "Uzun pisimli bolonez sos, parmesan ile servis.",
    stockState: "low",
    stockLabel: "Azaldi",
    prepMinutes: 15,
    visualTone: "amber",
    isPopular: true,
  },
  {
    id: "shrimp-casserole",
    name: "Karides Guvec",
    categoryId: "appetizer",
    price: 395,
    kind: "standard",
    description: "Tereyagli karides, sarimsak ve hafif aci dokunus.",
    stockState: "in_stock",
    stockLabel: "Stokta",
    prepMinutes: 14,
    visualTone: "rose",
    isFavorite: true,
  },
  {
    id: "caesar-salad",
    name: "Sezar Salata",
    categoryId: "appetizer",
    price: 245,
    kind: "standard",
    description: "Marul, parmesan, kruton ve sezar sos.",
    stockState: "in_stock",
    stockLabel: "Stokta",
    prepMinutes: 8,
    visualTone: "mint",
  },
  {
    id: "bread-basket",
    name: "Ekmek Sepeti",
    categoryId: "appetizer",
    price: 95,
    kind: "standard",
    description: "Sicak artisan ekmek secimi.",
    stockState: "in_stock",
    stockLabel: "Hizli",
    prepMinutes: 4,
    visualTone: "amber",
  },
  {
    id: "cheesecake",
    name: "San Sebastian",
    categoryId: "dessert",
    price: 225,
    kind: "standard",
    description: "Gunluk cikan sicak dilim cheesecake.",
    stockState: "in_stock",
    stockLabel: "Populer",
    prepMinutes: 5,
    visualTone: "rose",
    isPopular: true,
  },
  {
    id: "turkish-coffee",
    name: "Turk Kahvesi",
    categoryId: "drink",
    price: 95,
    kind: "standard",
    description: "Lokum ve su ile servis edilir.",
    stockState: "in_stock",
    stockLabel: "Stokta",
    prepMinutes: 5,
    visualTone: "plum",
  },
  {
    id: "lemonade",
    name: "Ev Limonatasi",
    categoryId: "drink",
    price: 110,
    kind: "standard",
    description: "Taze nane ve limon kabugu ile.",
    stockState: "in_stock",
    stockLabel: "Stokta",
    prepMinutes: 3,
    visualTone: "mint",
  },
  {
    id: "mineral-water",
    name: "Maden Suyu",
    categoryId: "drink",
    price: 45,
    kind: "standard",
    description: "Soguk servis edilir.",
    stockState: "in_stock",
    stockLabel: "Hazir",
    prepMinutes: 1,
    visualTone: "blue",
  },
  {
    id: "lokum-steak",
    name: "Dana Lokum",
    categoryId: "grill",
    price: 1250,
    kind: "weighted",
    description: "Gramajli premium dana lokum secimi.",
    stockState: "low",
    stockLabel: "Gramaj onayli",
    prepMinutes: 20,
    visualTone: "rose",
    quickWeightOptions: [250, 500, 750],
    isFavorite: true,
  },
  {
    id: "meze-service",
    name: "Meze Servisi",
    categoryId: "service",
    price: 0,
    kind: "service",
    description: "Tabak bazli karisik servis olusturur.",
    stockState: "in_stock",
    stockLabel: "Ozel akış",
    prepMinutes: 10,
    visualTone: "plum",
    tags: ["standart", "1 tabak", "5 tabak"],
  },
  {
    id: "breakfast-service",
    name: "Kahvalti Serpme Servisi",
    categoryId: "service",
    price: 0,
    kind: "service",
    description: "Tabakli paylasimli servis akisi.",
    stockState: "in_stock",
    stockLabel: "Servis builder",
    prepMinutes: 12,
    visualTone: "amber",
  },
];

export const customers: Customer[] = [
  {
    id: "cust-1",
    name: "Merve Aksoy",
    phone: "0532 555 11 22",
    loyaltyTier: "Altin",
    visitCount: 18,
    lastVisitAt: "2026-04-02T20:40:00.000Z",
    averageSpend: 1380,
    favoriteProductIds: ["truffle-burger", "cheesecake", "turkish-coffee"],
    notes: ["Burgerde sogansiz tercih ediyor", "Kahvede az seker"],
  },
  {
    id: "cust-2",
    name: "Kerem Demir",
    phone: "0551 230 44 10",
    loyaltyTier: "Gumus",
    visitCount: 7,
    lastVisitAt: "2026-03-28T18:20:00.000Z",
    averageSpend: 910,
    favoriteProductIds: ["salmon", "lemonade"],
    notes: ["Balikta ekstra limon istiyor"],
  },
  {
    id: "cust-3",
    name: "Ayse Can",
    phone: "0537 876 33 88",
    loyaltyTier: "Yeni",
    visitCount: 2,
    lastVisitAt: "2026-03-25T19:10:00.000Z",
    averageSpend: 540,
    favoriteProductIds: ["caesar-salad", "mineral-water"],
    notes: ["Toplanti icin sakin masa sever"],
    company: "Orion Studio",
  },
];

const productMap = Object.fromEntries(products.map((product) => [product.id, product]));

function line(
  productId: string,
  overrides: Partial<OrderItem> = {},
): OrderItem {
  const product = productMap[productId];
  return buildProductOrderItem(product, overrides);
}

function serviceChild(
  productId: string,
  quantity: number,
  plateNumber: number | null,
  note = "",
  modifiers: string[] = [],
): ServiceChildItem {
  const product = productMap[productId];
  return {
    id: `${productId}-${plateNumber ?? "main"}-${quantity}`,
    productId,
    name: product.name,
    quantity,
    unitPrice: product.price,
    totalPrice: product.price * quantity,
    plateNumber,
    note,
    modifiers,
  };
}

function serviceLine(
  productId: string,
  structure: "standard" | "1_plate" | "2_plate" | "3_plate" | "4_plate" | "5_plate",
  items: ServiceChildItem[],
  orderName: string,
  note: string,
): OrderItem {
  const product = productMap[productId];
  return line(productId, {
    name: orderName,
    kind: "service",
    unitPrice: 0,
    customizations: emptyCustomizations({ note }),
    service: {
      serviceName: product.name,
      orderName,
      structure,
      plateCount: structure === "standard" ? 0 : Number(structure[0]),
      note,
      items,
    },
  });
}

function order(
  id: string,
  label: string,
  status: OrderStatus,
  items: OrderItem[],
  updatedAt: string,
): TableOrder {
  const tableOrder: TableOrder = {
    id,
    label,
    status,
    items: items.map((item) => ({ ...cloneOrderItem(item), status })),
    totalPrice: 0,
    createdAt: updatedAt,
    updatedAt,
  };
  tableOrder.totalPrice = calculateOrderTotal(tableOrder);
  return tableOrder;
}

function splitPlan(parts: BillSplitPlan["parts"], createdAt: string): BillSplitPlan {
  return {
    id: `split-${createdAt}`,
    mode: "product",
    createdAt,
    parts,
    note: "Iki kisi icin urun bazli plan.",
  };
}

const tableSeed: RestaurantTable[] = [
  {
    id: "table-1",
    name: "Masa 01",
    zone: "Salon A",
    seats: 4,
    guestCount: 3,
    status: "preparing",
    openedAt: "2026-04-05T17:48:00.000Z",
    lastActionAt: "2026-04-05T18:22:00.000Z",
    customerId: "cust-1",
    draft: {
      items: [
        line("turkish-coffee", {
          quantity: 2,
          customizations: emptyCustomizations({
            note: "Biri orta sekerli",
            modifiers: ["az tuzlu"],
          }),
        }),
        line("lokum-steak", {
          quantity: 1,
          customizations: emptyCustomizations({
            grams: 500,
            note: "Az pisir",
            modifiers: ["acisiz"],
          }),
        }),
      ],
      editingOrderId: null,
      updatedAt: "2026-04-05T18:19:00.000Z",
    },
    orders: [
      order(
        "order-101",
        "Aksam Servisi",
        "preparing",
        [
          line("truffle-burger", {
            quantity: 2,
            customizations: emptyCustomizations({
              modifiers: ["domatessiz", "ekstra sos"],
            }),
          }),
          line("lemonade", { quantity: 3 }),
        ],
        "2026-04-05T18:05:00.000Z",
      ),
    ],
    payments: [
      {
        id: "pay-1",
        amount: 220,
        method: "cash",
        kind: "partial",
        note: "Icecekler icin ara odeme",
        createdAt: "2026-04-05T18:11:00.000Z",
      },
    ],
    splitPlans: [],
    reservation: null,
    referenceCode: "VIP-101",
    timedBilling: {
      enabled: false,
      startedAt: "2026-04-05T17:48:00.000Z",
      ratePerHour: 0,
    },
    logs: [],
  },
  {
    id: "table-2",
    name: "Masa 02",
    zone: "Salon A",
    seats: 2,
    guestCount: 0,
    status: "empty",
    openedAt: "2026-04-05T00:00:00.000Z",
    lastActionAt: "2026-04-05T17:00:00.000Z",
    customerId: null,
    draft: { items: [], editingOrderId: null, updatedAt: "2026-04-05T17:00:00.000Z" },
    orders: [],
    payments: [],
    splitPlans: [],
    reservation: {
      guestName: "Sena Ilgaz",
      phone: "0533 777 90 12",
      at: "2026-04-05T19:30:00.000Z",
      guestCount: 2,
      note: "Pencere kenari ve glutensiz secenek soracak.",
      channel: "phone",
    },
    logs: [],
  },
  {
    id: "table-3",
    name: "Masa 03",
    zone: "Salon B",
    seats: 4,
    guestCount: 2,
    status: "kitchen_sent",
    openedAt: "2026-04-05T18:10:00.000Z",
    lastActionAt: "2026-04-05T18:24:00.000Z",
    customerId: "cust-2",
    draft: { items: [], editingOrderId: null, updatedAt: "2026-04-05T18:24:00.000Z" },
    orders: [
      order(
        "order-102",
        "Balik Siparisi",
        "kitchen_sent",
        [
          line("salmon", {
            quantity: 1,
            customizations: emptyCustomizations({ modifiers: ["az tuzlu"] }),
          }),
          line("caesar-salad", { quantity: 1 }),
          line("mineral-water", { quantity: 2 }),
        ],
        "2026-04-05T18:24:00.000Z",
      ),
    ],
    payments: [],
    splitPlans: [],
    reservation: null,
    logs: [],
  },
  {
    id: "table-4",
    name: "Masa 04",
    zone: "Teras",
    seats: 6,
    guestCount: 5,
    status: "payment_pending",
    openedAt: "2026-04-05T17:15:00.000Z",
    lastActionAt: "2026-04-05T18:28:00.000Z",
    customerId: null,
    draft: { items: [], editingOrderId: null, updatedAt: "2026-04-05T18:28:00.000Z" },
    orders: [
      order(
        "order-103",
        "Teras Ana Fis",
        "served",
        [
          line("pasta-bolognese", { quantity: 2 }),
          line("shrimp-casserole", { quantity: 1 }),
          line("lemonade", { quantity: 3 }),
          line("cheesecake", { quantity: 2 }),
        ],
        "2026-04-05T18:03:00.000Z",
      ),
      order(
        "order-104",
        "Gece Servisi",
        "payment_pending",
        [
          serviceLine(
            "meze-service",
            "3_plate",
            [
              serviceChild("shrimp-casserole", 1, 1, "Az aci"),
              serviceChild("bread-basket", 1, 1),
              serviceChild("caesar-salad", 1, 2, "", ["sogansiz"]),
              serviceChild("mineral-water", 2, 3),
            ],
            "Meze Servisi - Aile",
            "Masanin ortasina servis",
          ),
        ],
        "2026-04-05T18:18:00.000Z",
      ),
    ],
    payments: [
      {
        id: "pay-2",
        amount: 500,
        method: "card",
        kind: "partial",
        note: "Ilk kisi karttan odedi",
        createdAt: "2026-04-05T18:20:00.000Z",
      },
    ],
    splitPlans: [
      splitPlan(
        [
          { id: "part-1", label: "Misafir 1", amount: 780, lineItemIds: ["order-103"] },
          { id: "part-2", label: "Misafir 2", amount: 835, lineItemIds: ["order-104"] },
        ],
        "2026-04-05T18:22:00.000Z",
      ),
    ],
    reservation: null,
    barcode: "BAR-004",
    logs: [],
  },
  {
    id: "table-5",
    name: "Masa 05",
    zone: "Salon B",
    seats: 4,
    guestCount: 2,
    status: "active",
    openedAt: "2026-04-05T18:02:00.000Z",
    lastActionAt: "2026-04-05T18:26:00.000Z",
    customerId: "cust-3",
    draft: {
      items: [
        line("breakfast-service", {
          name: "Mini Kahvalti Servisi",
          kind: "service",
          service: {
            serviceName: "Kahvalti Serpme Servisi",
            orderName: "Mini Kahvalti Servisi",
            structure: "2_plate",
            plateCount: 2,
            note: "Caya limon eklensin",
            items: [
              serviceChild("bread-basket", 1, 1),
              serviceChild("caesar-salad", 1, 2, "", ["domatessiz"]),
              serviceChild("turkish-coffee", 2, 2),
            ],
          },
        }),
      ],
      editingOrderId: null,
      updatedAt: "2026-04-05T18:26:00.000Z",
    },
    orders: [
      order(
        "order-105",
        "Hafif Menu",
        "served",
        [line("caesar-salad", { quantity: 2 }), line("lemonade", { quantity: 2 })],
        "2026-04-05T18:09:00.000Z",
      ),
    ],
    payments: [],
    splitPlans: [],
    reservation: null,
    logs: [],
  },
  {
    id: "table-6",
    name: "Bar 01",
    zone: "Bar",
    seats: 2,
    guestCount: 1,
    status: "ready",
    openedAt: "2026-04-05T18:18:00.000Z",
    lastActionAt: "2026-04-05T18:30:00.000Z",
    customerId: null,
    draft: { items: [], editingOrderId: null, updatedAt: "2026-04-05T18:30:00.000Z" },
    orders: [
      order(
        "order-106",
        "Bar Hizli Siparis",
        "ready",
        [line("turkish-coffee", { quantity: 1 }), line("cheesecake", { quantity: 1 })],
        "2026-04-05T18:30:00.000Z",
      ),
    ],
    payments: [],
    splitPlans: [],
    reservation: null,
    logs: [],
  },
  {
    id: "table-7",
    name: "Masa 07",
    zone: "Salon A",
    seats: 4,
    guestCount: 0,
    status: "empty",
    openedAt: "2026-04-05T00:00:00.000Z",
    lastActionAt: "2026-04-05T16:50:00.000Z",
    customerId: null,
    draft: { items: [], editingOrderId: null, updatedAt: "2026-04-05T16:50:00.000Z" },
    orders: [],
    payments: [],
    splitPlans: [],
    reservation: null,
    logs: [],
  },
  {
    id: "table-8",
    name: "VIP 1",
    zone: "VIP",
    seats: 8,
    guestCount: 4,
    status: "served",
    openedAt: "2026-04-05T17:05:00.000Z",
    lastActionAt: "2026-04-05T18:25:00.000Z",
    customerId: "cust-1",
    draft: { items: [], editingOrderId: null, updatedAt: "2026-04-05T18:25:00.000Z" },
    orders: [
      order(
        "order-107",
        "VIP Ozel Masa",
        "served",
        [line("lokum-steak", { customizations: emptyCustomizations({ grams: 750 }) })],
        "2026-04-05T18:25:00.000Z",
      ),
    ],
    payments: [],
    splitPlans: [],
    reservation: null,
    referenceCode: "VIP-ROOM",
    timedBilling: {
      enabled: true,
      startedAt: "2026-04-05T17:05:00.000Z",
      ratePerHour: 320,
    },
    logs: [],
  },
];

const printerJobSeed: PrinterJob[] = [
  {
    id: "print-101",
    venueId: "venue-demo",
    tableId: "table-4",
    tableName: "Masa 04",
    orderId: "order-104",
    orderReference: "Gece Servisi",
    printType: "adisyon",
    printerTarget: "Kasa Adisyon Yazicisi",
    status: "printed",
    items: [
      {
        id: "order-104-line-1",
        name: "Meze Servisi - Aile",
        quantity: 1,
        totalPrice: 835,
      },
    ],
    totalAmount: 835,
    requestedBy: "Restaurant Ops",
    source: "manual_action",
    createdAt: "2026-04-05T18:23:00.000Z",
    printedAt: "2026-04-05T18:23:15.000Z",
  },
];

export function createInitialState(): RestaurantStoreState {
  const venueId = "venue-demo";
  return {
    products: [...products],
    categories: [...productCategories],
    customers: [...customers],
    printerJobs: [...printerJobSeed],
    tables: tableSeed.map((table) => {
      const withLog = addLog(table, {
        type: "seed",
        title: "Masa acildi",
        description: `${table.name} mock veri ile hazirlandi.`,
        severity: "info",
      });
      return {
        ...withLog,
        venueId,
        activeSessionId: `${table.id}-session`,
        version: 1,
        status: deriveTableStatus(withLog),
      };
    }),
    meta: {
      venueId,
      source: "mock",
      fetchedAt: new Date().toISOString(),
      snapshotVersion: "snapshot-demo-1",
      conflictStrategy: "server-wins",
      optimisticEnabled: true,
    },
  };
}
