import 'package:latlong2/latlong.dart';

abstract final class SellerCargoGeoData {
  static const List<String> provinces = <String>[
    'Adana',
    'Adıyaman',
    'Afyonkarahisar',
    'Ağrı',
    'Aksaray',
    'Amasya',
    'Ankara',
    'Antalya',
    'Ardahan',
    'Artvin',
    'Aydın',
    'Balıkesir',
    'Bartın',
    'Batman',
    'Bayburt',
    'Bilecik',
    'Bingöl',
    'Bitlis',
    'Bolu',
    'Burdur',
    'Bursa',
    'Çanakkale',
    'Çankırı',
    'Çorum',
    'Denizli',
    'Diyarbakır',
    'Düzce',
    'Edirne',
    'Elazığ',
    'Erzincan',
    'Erzurum',
    'Eskişehir',
    'Gaziantep',
    'Giresun',
    'Gümüşhane',
    'Hakkari',
    'Hatay',
    'Iğdır',
    'Isparta',
    'İstanbul',
    'İzmir',
    'Kahramanmaraş',
    'Karabük',
    'Karaman',
    'Kars',
    'Kastamonu',
    'Kayseri',
    'Kırıkkale',
    'Kırklareli',
    'Kırşehir',
    'Kilis',
    'Kocaeli',
    'Konya',
    'Kütahya',
    'Malatya',
    'Manisa',
    'Mardin',
    'Mersin',
    'Muğla',
    'Muş',
    'Nevşehir',
    'Niğde',
    'Ordu',
    'Osmaniye',
    'Rize',
    'Sakarya',
    'Samsun',
    'Siirt',
    'Sinop',
    'Sivas',
    'Şanlıurfa',
    'Şırnak',
    'Tekirdağ',
    'Tokat',
    'Trabzon',
    'Tunceli',
    'Uşak',
    'Van',
    'Yalova',
    'Yozgat',
    'Zonguldak',
  ];

  static const Map<String, List<String>> districtsByProvince =
      <String, List<String>>{
        'İstanbul': <String>[
          'Adalar',
          'Arnavutköy',
          'Ataşehir',
          'Avcılar',
          'Bağcılar',
          'Bahçelievler',
          'Bakırköy',
          'Başakşehir',
          'Bayrampaşa',
          'Beşiktaş',
          'Beykoz',
          'Beylikdüzü',
          'Beyoğlu',
          'Büyükçekmece',
          'Çatalca',
          'Çekmeköy',
          'Esenler',
          'Esenyurt',
          'Eyüpsultan',
          'Fatih',
          'Gaziosmanpaşa',
          'Güngören',
          'Kadıköy',
          'Kağıthane',
          'Kartal',
          'Küçükçekmece',
          'Maltepe',
          'Pendik',
          'Sancaktepe',
          'Sarıyer',
          'Silivri',
          'Sultanbeyli',
          'Sultangazi',
          'Şile',
          'Şişli',
          'Tuzla',
          'Ümraniye',
          'Üsküdar',
          'Zeytinburnu',
        ],
        'Ankara': <String>[
          'Altındağ',
          'Ayaş',
          'Bala',
          'Beypazarı',
          'Çankaya',
          'Etimesgut',
          'Gölbaşı',
          'Kahramankazan',
          'Keçiören',
          'Mamak',
          'Polatlı',
          'Sincan',
          'Yenimahalle',
        ],
        'İzmir': <String>[
          'Aliağa',
          'Balçova',
          'Bayraklı',
          'Bornova',
          'Buca',
          'Çeşme',
          'Gaziemir',
          'Karabağlar',
          'Karşıyaka',
          'Konak',
          'Menemen',
          'Narlıdere',
          'Torbalı',
        ],
        'Bursa': <String>[
          'Gemlik',
          'Gürsu',
          'İnegöl',
          'Mudanya',
          'Nilüfer',
          'Osmangazi',
          'Yıldırım',
        ],
        'Antalya': <String>[
          'Aksu',
          'Alanya',
          'Döşemealtı',
          'Kepez',
          'Konyaaltı',
          'Kumluca',
          'Manavgat',
          'Muratpaşa',
          'Serik',
        ],
        'Hatay': <String>[
          'Altınözü',
          'Antakya',
          'Arsuz',
          'Belen',
          'Defne',
          'Dörtyol',
          'Erzin',
          'Hassa',
          'İskenderun',
          'Kırıkhan',
          'Kumlu',
          'Payas',
          'Reyhanlı',
          'Samandağ',
          'Yayladağı',
        ],
        'Adana': <String>[
          'Çukurova',
          'Sarıçam',
          'Seyhan',
          'Yüreğir',
          'Ceyhan',
          'Kozan',
        ],
        'Mersin': <String>[
          'Akdeniz',
          'Erdemli',
          'Mezitli',
          'Silifke',
          'Tarsus',
          'Toroslar',
          'Yenişehir',
        ],
      };

  static const Map<String, LatLng> centers = <String, LatLng>{
    'İstanbul': LatLng(41.0082, 28.9784),
    'Ankara': LatLng(39.9334, 32.8597),
    'İzmir': LatLng(38.4237, 27.1428),
    'Bursa': LatLng(40.1828, 29.0663),
    'Antalya': LatLng(36.8969, 30.7133),
    'Hatay': LatLng(36.2021, 36.1606),
    'Adana': LatLng(37.0017, 35.3289),
    'Mersin': LatLng(36.8121, 34.6415),
    'Kocaeli': LatLng(40.7654, 29.9408),
    'Konya': LatLng(37.8746, 32.4932),
    'Gaziantep': LatLng(37.0662, 37.3833),
    'Eskişehir': LatLng(39.7767, 30.5206),
    'Trabzon': LatLng(41.0015, 39.7178),
  };


  static List<String> districtsFor(String province) {
    final options = districtsByProvince[province];
    if (options == null || options.isEmpty) return const <String>['Merkez'];
    return List<String>.from(options);
  }

  static String defaultDistrict(String province) {
    final options = districtsFor(province);
    return options.isNotEmpty ? options.first : 'Merkez';
  }
}
