-- Satıcı şifre kurtarma. BOŞ bir SQL Editor (New query) içine yapıştırın.
-- Başka bir sekmedeki SQL ile birleştirmeyin.

create extension if not exists pgcrypto;

create table if not exists public.store_recovery_codes (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(seller_id) on delete cascade,
  code_hash text not null,
  created_at timestamptz not null default timezone('utc', now()),
  created_by uuid,
  used_at timestamptz,
  constraint store_recovery_codes_hash_unique unique (code_hash)
);

create index if not exists store_recovery_codes_store_unused_idx
  on public.store_recovery_codes (store_id)
  where used_at is null;

create table if not exists public.store_recovery_attempts (
  id bigint generated by default as identity primary key,
  identifier_hash text not null,
  created_at timestamptz not null default timezone('utc', now()),
  success boolean not null default false
);

create index if not exists store_recovery_attempts_ident_idx
  on public.store_recovery_attempts (identifier_hash, created_at desc);

alter table public.store_recovery_codes enable row level security;
alter table public.store_recovery_attempts enable row level security;

drop policy if exists store_recovery_codes_admin_select on public.store_recovery_codes;
create policy store_recovery_codes_admin_select
on public.store_recovery_codes
for select
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and (
        lower(coalesce(u.role, '')) in ('admin', 'super_admin')
        or lower(coalesce(u.role, '')) like 'admin_%'
      )
  )
);

revoke all on public.store_recovery_codes from public, anon;
grant select on public.store_recovery_codes to authenticated;
revoke all on public.store_recovery_attempts from public, anon, authenticated;

create or replace function public._store_recovery_hash(p_store_id uuid, p_code text)
returns text
language sql
immutable
set search_path = public, extensions
as $fn_hash$
  select encode(
    digest(
      p_store_id::text || ':' || upper(trim(both from coalesce(p_code, ''))),
      'sha256'
    ),
    'hex'
  );
$fn_hash$;

create or replace function public._store_recovery_normalize_phone(p_phone text)
returns text
language sql
immutable
as $fn_phone$
  select regexp_replace(coalesce(p_phone, ''), '[^0-9]', '', 'g');
$fn_phone$;

create or replace function public.admin_issue_store_recovery_codes(p_store_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $fn_issue$
declare
  v_actor uuid := auth.uid();
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  bytes bytea;
  code text;
  i int;
  n int;
  idx int;
  codes jsonb := jsonb_build_array();
begin
  if v_actor is null then
    raise exception 'not authenticated';
  end if;
  if not exists (
    select 1
    from public.users u
    where u.id = v_actor
      and (
        lower(coalesce(u.role, '')) in ('admin', 'super_admin')
        or lower(coalesce(u.role, '')) like 'admin_%'
      )
  ) then
    raise exception 'not authorized';
  end if;
  if p_store_id is null or not exists (
    select 1 from public.stores s where s.seller_id = p_store_id
  ) then
    raise exception 'store not found';
  end if;

  delete from public.store_recovery_codes
  where store_id = p_store_id
    and used_at is null;

  for n in 1..5 loop
    loop
      bytes := gen_random_bytes(8);
      code := '';
      for i in 0..7 loop
        idx := get_byte(bytes, i) % length(alphabet);
        code := code || substr(alphabet, idx + 1, 1);
        if i = 3 then
          code := code || '-';
        end if;
      end loop;
      exit when not exists (
        select 1
        from public.store_recovery_codes c
        where c.code_hash = public._store_recovery_hash(p_store_id, code)
      );
    end loop;

    insert into public.store_recovery_codes (
      store_id,
      code_hash,
      created_by
    ) values (
      p_store_id,
      public._store_recovery_hash(p_store_id, code),
      v_actor
    );
    codes := codes || jsonb_build_array(code);
  end loop;

  return jsonb_build_object('ok', true, 'store_id', p_store_id, 'codes', codes);
end;
$fn_issue$;

create or replace function public.seller_reset_password_with_recovery_code(
  p_identifier text,
  p_code text,
  p_new_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $fn_reset$
declare
  v_ident text := lower(trim(both from coalesce(p_identifier, '')));
  v_phone text := public._store_recovery_normalize_phone(p_identifier);
  v_ident_hash text;
  v_attempts int;
  v_store_id uuid;
  v_hash text;
  v_code_id uuid;
begin
  if length(coalesce(p_new_password, '')) < 6 then
    raise exception 'password too short';
  end if;
  if length(coalesce(p_code, '')) < 8 then
    raise exception 'invalid code';
  end if;
  if v_ident = '' then
    raise exception 'identifier required';
  end if;

  v_ident_hash := encode(digest(v_ident, 'sha256'), 'hex');

  select count(*) into v_attempts
  from public.store_recovery_attempts a
  where a.identifier_hash = v_ident_hash
    and a.created_at > timezone('utc', now()) - interval '15 minutes'
    and a.success = false;
  if v_attempts >= 8 then
    raise exception 'too many attempts';
  end if;

  select s.seller_id
    into v_store_id
  from public.stores s
  left join public.users u on u.id = s.seller_id
  where lower(trim(both from coalesce(s.email, ''))) = v_ident
     or lower(trim(both from coalesce(u.email, ''))) = v_ident
     or public._store_recovery_normalize_phone(s.phone) = v_phone
     or public._store_recovery_normalize_phone(u.phone) = v_phone
  order by s.created_at desc
  limit 1;

  if v_store_id is null then
    insert into public.store_recovery_attempts (identifier_hash, success)
    values (v_ident_hash, false);
    raise exception 'invalid recovery';
  end if;

  v_hash := public._store_recovery_hash(v_store_id, p_code);

  select c.id into v_code_id
  from public.store_recovery_codes c
  where c.store_id = v_store_id
    and c.code_hash = v_hash
    and c.used_at is null
  limit 1;

  if v_code_id is null then
    insert into public.store_recovery_attempts (identifier_hash, success)
    values (v_ident_hash, false);
    raise exception 'invalid recovery';
  end if;

  update auth.users
  set encrypted_password = crypt(p_new_password, gen_salt('bf')),
      updated_at = timezone('utc', now())
  where id = v_store_id;

  if not found then
    raise exception 'auth user missing';
  end if;

  update public.store_recovery_codes
  set used_at = timezone('utc', now())
  where id = v_code_id;

  insert into public.store_recovery_attempts (identifier_hash, success)
  values (v_ident_hash, true);

  return jsonb_build_object('ok', true, 'store_id', v_store_id);
end;
$fn_reset$;

revoke all on function public.admin_issue_store_recovery_codes(uuid) from public;
revoke all on function public.admin_issue_store_recovery_codes(uuid) from anon;
grant execute on function public.admin_issue_store_recovery_codes(uuid)
  to authenticated;

revoke all on function public.seller_reset_password_with_recovery_code(text, text, text)
  from public;
grant execute on function public.seller_reset_password_with_recovery_code(text, text, text)
  to anon, authenticated;
