-- Public investor inquiry intake. No public SELECT; insert via RPC only.

create extension if not exists pgcrypto;

create table if not exists public.investor_inquiries (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  company text,
  email text not null,
  phone text,
  investor_type text,
  interest_area text,
  message text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.investor_inquiry_submit_log (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  client_addr inet,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_investor_inquiry_submit_log_addr
  on public.investor_inquiry_submit_log (client_addr, created_at desc);

alter table public.investor_inquiries enable row level security;
alter table public.investor_inquiry_submit_log enable row level security;

drop policy if exists investor_inquiries_admin_select on public.investor_inquiries;
create policy investor_inquiries_admin_select
on public.investor_inquiries
for select
using (
  exists (
    select 1
    from public.users u
    where u.id = auth.uid()
      and (
        lower(coalesce(u.role, '')) in ('admin', 'super_admin', 'owner', 'admin_investor')
        or coalesce(u.role, '') like 'admin_%'
      )
  )
);

revoke all on public.investor_inquiries from public, anon, authenticated;
grant select on public.investor_inquiries to authenticated;
revoke all on public.investor_inquiry_submit_log from public, anon, authenticated;

create or replace function public.submit_investor_inquiry(
  p_full_name text,
  p_company text,
  p_email text,
  p_phone text,
  p_investor_type text,
  p_interest_area text,
  p_message text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(trim(coalesce(p_email, '')));
  v_name text := trim(coalesce(p_full_name, ''));
  v_hash text;
  v_addr inet := inet_client_addr();
  v_recent int := 0;
begin
  if v_name = '' or char_length(v_name) > 120 then
    return jsonb_build_object('ok', false, 'error', 'invalid_name');
  end if;
  if v_email = '' or v_email !~ '^[^@]+@[^@]+\.[^@]+$' or char_length(v_email) > 160 then
    return jsonb_build_object('ok', false, 'error', 'invalid_email');
  end if;

  v_hash := encode(digest(v_email, 'sha256'), 'hex');
  insert into public.investor_inquiry_submit_log (email_hash, client_addr)
  values (v_hash, v_addr);

  select count(*)::int
  into v_recent
  from public.investor_inquiry_submit_log
  where created_at > timezone('utc', now()) - interval '10 minutes'
    and (
      (v_addr is not null and client_addr = v_addr)
      or (v_addr is null and email_hash = v_hash)
    );

  if v_recent > 8 then
    return jsonb_build_object('ok', false, 'error', 'rate_limited');
  end if;

  insert into public.investor_inquiries (
    full_name, company, email, phone, investor_type, interest_area, message
  ) values (
    v_name,
    nullif(trim(coalesce(p_company, '')), ''),
    v_email,
    nullif(trim(coalesce(p_phone, '')), ''),
    nullif(trim(coalesce(p_investor_type, '')), ''),
    nullif(trim(coalesce(p_interest_area, '')), ''),
    nullif(left(trim(coalesce(p_message, '')), 4000), '')
  );

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.submit_investor_inquiry(
  text, text, text, text, text, text, text
) from public;
grant execute on function public.submit_investor_inquiry(
  text, text, text, text, text, text, text
) to anon, authenticated;
