-- IHIZ business serial + owner-proven link. Serial is NOT on public stores
-- columns so anon select * cannot dump codes. Lookup is exact-match RPC only.

create extension if not exists pgcrypto;

create table if not exists public.store_business_serials (
  store_id uuid primary key references public.stores(seller_id) on delete cascade,
  business_serial_no text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  constraint store_business_serials_format
    check (business_serial_no ~ '^ISL-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{6}$')
);

create table if not exists public.ihiz_business_serial_lookup_log (
  id bigint generated by default as identity primary key,
  serial_hash text not null,
  client_addr inet,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_ihiz_business_serial_lookup_log_addr
  on public.ihiz_business_serial_lookup_log (client_addr, created_at desc);

alter table public.store_business_serials enable row level security;
alter table public.ihiz_business_serial_lookup_log enable row level security;

drop policy if exists store_business_serials_owner_select on public.store_business_serials;
create policy store_business_serials_owner_select
on public.store_business_serials
for select
using (
  store_id = auth.uid()
  or public.ihiz_actor_is_admin(auth.uid())
);

drop policy if exists ihiz_business_serial_lookup_log_admin
  on public.ihiz_business_serial_lookup_log;
create policy ihiz_business_serial_lookup_log_admin
on public.ihiz_business_serial_lookup_log
for select
using (public.ihiz_actor_is_admin(auth.uid()));

grant select on public.store_business_serials to authenticated;
revoke all on public.ihiz_business_serial_lookup_log from public, anon, authenticated;
grant select on public.ihiz_business_serial_lookup_log to authenticated;

create or replace function public.ihiz_normalize_business_serial(p_code text)
returns text
language sql
immutable
as $$
  select upper(trim(both from coalesce(p_code, '')));
$$;

create or replace function public.ihiz_generate_business_serial()
returns text
language plpgsql
set search_path = public, extensions
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  bytes bytea;
  code text;
  i int;
  idx int;
begin
  loop
    bytes := gen_random_bytes(6);
    code := 'ISL-';
    for i in 0..5 loop
      idx := get_byte(bytes, i) % length(alphabet);
      code := code || substr(alphabet, idx + 1, 1);
    end loop;
    exit when not exists (
      select 1
      from public.store_business_serials s
      where s.business_serial_no = code
    );
  end loop;
  return code;
end;
$$;

create or replace function public.stores_assign_business_serial()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  insert into public.store_business_serials (store_id, business_serial_no)
  values (new.seller_id, public.ihiz_generate_business_serial())
  on conflict (store_id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_stores_assign_business_serial on public.stores;
create trigger trg_stores_assign_business_serial
after insert on public.stores
for each row execute function public.stores_assign_business_serial();

insert into public.store_business_serials (store_id, business_serial_no)
select s.seller_id, public.ihiz_generate_business_serial()
from public.stores s
where not exists (
  select 1
  from public.store_business_serials x
  where x.store_id = s.seller_id
);

create or replace function public.lookup_store_by_business_serial(p_serial text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := public.ihiz_normalize_business_serial(p_serial);
  v_hash text;
  v_addr inet := inet_client_addr();
  v_recent int := 0;
  v_store_id uuid;
  v_name text;
  v_city text;
  v_district text;
begin
  if v_code is null or v_code = '' or v_code !~ '^ISL-[A-Z0-9]{6}$' then
    return jsonb_build_object('found', false, 'error', 'not_found');
  end if;

  v_hash := encode(digest(v_code, 'sha256'), 'hex');
  insert into public.ihiz_business_serial_lookup_log (serial_hash, client_addr)
  values (v_hash, v_addr);

  select count(*)::int
  into v_recent
  from public.ihiz_business_serial_lookup_log
  where created_at > timezone('utc', now()) - interval '10 minutes'
    and (
      (v_addr is not null and client_addr = v_addr)
      or (v_addr is null and client_addr is null and serial_hash = v_hash)
    );

  if v_recent > 30 then
    return jsonb_build_object('found', false, 'error', 'rate_limited');
  end if;

  select serials.store_id, s.business_name, s.city, s.district
  into v_store_id, v_name, v_city, v_district
  from public.store_business_serials serials
  join public.stores s on s.seller_id = serials.store_id
  where serials.business_serial_no = v_code
  limit 1;

  if not found then
    return jsonb_build_object('found', false, 'error', 'not_found');
  end if;

  return jsonb_build_object(
    'found', true,
    'business_name', v_name,
    'city', v_city,
    'district', v_district
  );
end;
$$;

revoke all on function public.lookup_store_by_business_serial(text) from public;
grant execute on function public.lookup_store_by_business_serial(text)
  to anon, authenticated;

create or replace function public.link_ihiz_business_by_serial(p_serial text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_code text := public.ihiz_normalize_business_serial(p_serial);
  v_store_id uuid;
  v_name text;
  v_row public.ihiz_business_accounts%rowtype;
begin
  if v_uid is null then
    raise exception 'auth_required';
  end if;
  if v_code is null or v_code !~ '^ISL-[A-Z0-9]{6}$' then
    raise exception 'not_found';
  end if;

  select serials.store_id, s.business_name
  into v_store_id, v_name
  from public.store_business_serials serials
  join public.stores s on s.seller_id = serials.store_id
  where serials.business_serial_no = v_code
  limit 1;

  if v_store_id is null then
    raise exception 'not_found';
  end if;
  if v_store_id <> v_uid then
    raise exception 'store_forbidden';
  end if;

  insert into public.ihiz_business_accounts (
    seller_id, store_id, status, business_name, activated_at
  ) values (
    v_uid, v_store_id, 'active', v_name, timezone('utc', now())
  )
  on conflict (seller_id) do update set
    store_id = excluded.store_id,
    business_name = excluded.business_name,
    status = 'active',
    activated_at = coalesce(
      public.ihiz_business_accounts.activated_at,
      timezone('utc', now())
    ),
    updated_at = timezone('utc', now())
  returning * into v_row;

  return jsonb_build_object(
    'ok', true,
    'store_id', v_row.store_id,
    'status', v_row.status,
    'business_name', v_row.business_name
  );
end;
$$;

revoke all on function public.link_ihiz_business_by_serial(text) from public;
grant execute on function public.link_ihiz_business_by_serial(text) to authenticated;

drop function if exists public.ensure_store_business_serial_no();

create or replace function public.ensure_store_business_serial_no(
  p_store_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_store uuid := coalesce(p_store_id, v_uid);
  v_code text;
  v_name text;
  v_status text;
begin
  if v_uid is null then
    raise exception 'auth_required';
  end if;
  if v_store is null then
    raise exception 'store_forbidden';
  end if;
  if not (
    public.ihiz_actor_owns_store(v_store, v_uid)
    or public.ihiz_actor_is_admin(v_uid)
  ) then
    raise exception 'store_forbidden';
  end if;

  insert into public.store_business_serials (store_id, business_serial_no)
  values (v_store, public.ihiz_generate_business_serial())
  on conflict (store_id) do nothing;

  select serials.business_serial_no, s.business_name
  into v_code, v_name
  from public.store_business_serials serials
  join public.stores s on s.seller_id = serials.store_id
  where serials.store_id = v_store
  limit 1;

  select a.status
  into v_status
  from public.ihiz_business_accounts a
  where a.store_id = v_store
  limit 1;

  return jsonb_build_object(
    'ok', true,
    'store_id', v_store,
    'business_serial_no', v_code,
    'business_name', v_name,
    'ihiz_status', v_status
  );
end;
$$;

revoke all on function public.ensure_store_business_serial_no(uuid) from public;
grant execute on function public.ensure_store_business_serial_no(uuid) to authenticated;

create or replace function public.ihiz_ops_task_json(t public.ihiz_delivery_tasks)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'id', t.id,
    'tracking_code', t.tracking_code,
    'status', t.status,
    'source_type', t.source_type,
    'pickup_name', t.pickup_name,
    'dropoff_name', t.dropoff_name,
    'pickup_phone', t.pickup_phone,
    'dropoff_phone', t.dropoff_phone,
    'assigned_courier_id', t.assigned_courier_id,
    'created_at', t.created_at,
    'picked_up_at', t.picked_up_at,
    'delivered_at', t.delivered_at
  );
$$;

create or replace function public.list_ihiz_business_ops(p_store_id uuid default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_admin boolean;
  v_target uuid;
  v_payload jsonb := '[]'::jsonb;
begin
  if v_uid is null then
    raise exception 'auth_required';
  end if;
  v_admin := public.ihiz_actor_is_admin(v_uid);

  if p_store_id is not null then
    if not (public.ihiz_actor_owns_store(p_store_id, v_uid) or v_admin) then
      raise exception 'forbidden';
    end if;
    v_target := p_store_id;
  elsif not v_admin then
    v_target := v_uid;
  end if;

  select coalesce(
    jsonb_agg(store_row.item order by store_row.business_name),
    '[]'::jsonb
  )
  into v_payload
  from (
    select
      s.business_name,
      jsonb_build_object(
        'store_id', s.seller_id,
        'business_name', s.business_name,
        'serial', serials.business_serial_no,
        'status', a.status,
        'incoming_count', (
          select count(*)::int
          from public.ihiz_delivery_tasks t
          where t.store_id = s.seller_id
            and t.status in ('created', 'preparing')
        ),
        'outgoing_count', (
          select count(*)::int
          from public.ihiz_delivery_tasks t
          where t.store_id = s.seller_id
            and t.source_type = 'ibul_order'
            and t.status not in ('delivered', 'cancelled')
        ),
        'sent_count', (
          select count(*)::int
          from public.ihiz_delivery_tasks t
          where t.store_id = s.seller_id
            and t.source_type = 'package_send'
        ),
        'active_count', (
          select count(*)::int
          from public.ihiz_delivery_tasks t
          where t.store_id = s.seller_id
            and t.status not in ('delivered', 'cancelled')
        ),
        'courier_count', (
          select count(*)::int
          from public.ihiz_store_couriers sc
          where sc.store_id = s.seller_id
            and sc.is_selected = true
        ),
        'incoming', (
          select coalesce(jsonb_agg(public.ihiz_ops_task_json(t) order by t.created_at desc), '[]'::jsonb)
          from (
            select *
            from public.ihiz_delivery_tasks t
            where t.store_id = s.seller_id
              and t.status in ('created', 'preparing')
            order by t.created_at desc
            limit 50
          ) t
        ),
        'outgoing', (
          select coalesce(jsonb_agg(public.ihiz_ops_task_json(t) order by t.created_at desc), '[]'::jsonb)
          from (
            select *
            from public.ihiz_delivery_tasks t
            where t.store_id = s.seller_id
              and t.source_type = 'ibul_order'
              and t.status not in ('delivered', 'cancelled')
            order by t.created_at desc
            limit 50
          ) t
        ),
        'sent', (
          select coalesce(jsonb_agg(public.ihiz_ops_task_json(t) order by t.created_at desc), '[]'::jsonb)
          from (
            select *
            from public.ihiz_delivery_tasks t
            where t.store_id = s.seller_id
              and t.source_type = 'package_send'
            order by t.created_at desc
            limit 50
          ) t
        ),
        'active', (
          select coalesce(jsonb_agg(public.ihiz_ops_task_json(t) order by t.created_at desc), '[]'::jsonb)
          from (
            select *
            from public.ihiz_delivery_tasks t
            where t.store_id = s.seller_id
              and t.status not in ('delivered', 'cancelled')
            order by t.created_at desc
            limit 50
          ) t
        ),
        'couriers', (
          select coalesce(
            jsonb_agg(
              jsonb_build_object(
                'courier_user_id', sc.courier_user_id,
                'full_name', app.full_name,
                'city', app.city,
                'is_active', sc.is_active,
                'is_selected', sc.is_selected
              )
              order by app.full_name
            ),
            '[]'::jsonb
          )
          from public.ihiz_store_couriers sc
          left join public.ihiz_courier_applications app
            on app.user_id = sc.courier_user_id
          where sc.store_id = s.seller_id
        )
      ) as item
    from public.stores s
    left join public.store_business_serials serials on serials.store_id = s.seller_id
    left join public.ihiz_business_accounts a on a.store_id = s.seller_id
    where (
      v_target is not null and s.seller_id = v_target
    ) or (
      v_target is null
      and v_admin
      and a.id is not null
    )
  ) store_row;

  return jsonb_build_object('ok', true, 'stores', v_payload);
end;
$$;

revoke all on function public.ihiz_ops_task_json(public.ihiz_delivery_tasks) from public;
revoke all on function public.list_ihiz_business_ops(uuid) from public;
revoke all on function public.ihiz_generate_business_serial() from public;
grant execute on function public.list_ihiz_business_ops(uuid) to authenticated;
